# Generated by Django 3.1.7 on 2021-04-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kelid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('160', '160A'), ('250', '250A'), ('400', '400A'), ('630', '630A')], max_length=3)),
                ('brand', models.CharField(choices=[('CH', 'چانت'), ('PF', 'پارس فانال')], max_length=2)),
            ],
        ),
    ]
